export const Lines = [
  { id: 1, img: "/assets/green-lines/l-1.png", offset: "right-20" },
  { id: 2, img: "/assets/green-lines/l-2.png", offset: "right-16" },
  { id: 3, img: "/assets/green-lines/l-3.png", offset: "right-20" },
  { id: 4, img: "/assets/green-lines/l-4.png", offset: "right-7" },
  { id: 5, img: "/assets/green-lines/l-5.png" },
  { id: 6, img: "/assets/green-lines/l-6.png" },
  { id: 7, img: "/assets/green-lines/l-7.png" },
  { id: 8, img: "/assets/green-lines/l-8.png" },
  { id: 9, img: "/assets/green-lines/l-9.png" },
  { id: 10, img: "/assets/green-lines/l-10.png" },
  { id: 11, img: "/assets/green-lines/l-11.png" },
  { id: 12, img: "/assets/green-lines/l-12.png" },
  { id: 13, img: "/assets/green-lines/l-13.png" },
  { id: 14, img: "/assets/green-lines/l-14.png" },
  { id: 15, img: "/assets/green-lines/l-15.png" },
  { id: 16, img: "/assets/green-lines/l-16.png" },
];

export const WhiteLines = [
  { id: 1, img: "/assets/white-lines/l-1.png", offset: "right-20" },
  { id: 2, img: "/assets/white-lines/l-2.png", offset: "right-16" },
  { id: 3, img: "/assets/white-lines/l-3.png", offset: "right-20" },
  { id: 4, img: "/assets/white-lines/l-4.png", offset: "right-7" },
  { id: 5, img: "/assets/white-lines/l-5.png" },
  { id: 6, img: "/assets/white-lines/l-6.png" },
  { id: 7, img: "/assets/white-lines/l-7.png" },
  { id: 8, img: "/assets/white-lines/l-8.png" },
  { id: 9, img: "/assets/white-lines/l-9.png" },
  { id: 10, img: "/assets/white-lines/l-10.png" },
  { id: 11, img: "/assets/white-lines/l-11.png" },
  { id: 12, img: "/assets/white-lines/l-12.png" },
  { id: 13, img: "/assets/white-lines/l-13.png" },
  { id: 14, img: "/assets/white-lines/l-14.png" },
  { id: 15, img: "/assets/white-lines/l-15.png" },
  { id: 16, img: "/assets/white-lines/l-16.png" },
];

export const HomeLines: any[] = [
  {
    id: 1,
    img: "/assets/home-page-lines/Vector.png",
    right: "right-[24.5rem]",
    bottom: "-bottom-2",
  },
  {
    id: 2,
    img: "/assets/home-page-lines/Vector (1).png",
    right: "right-[21.5rem]",
    bottom: "-bottom-[3rem]",
  },
  {
    id: 3,
    img: "/assets/home-page-lines/Vector (2).png",
    right: "right-[18rem]",
    bottom: "-bottom-[5rem]",
  },
  {
    id: 4,
    img: "/assets/home-page-lines/Vector (3).png",
    right: "right-[14.5rem]",
    bottom: "-bottom-[7rem]",
  },
  {
    id: 5,
    img: "/assets/home-page-lines/Vector (4).png",
    right: "right-[11rem]",
    bottom: "-bottom-[9rem]",
  },
  {
    id: 6,
    img: "/assets/home-page-lines/Vector (5).png",
    right: "right-[8rem]",
    bottom: "-bottom-[10rem]",
  },
  {
    id: 7,
    img: "/assets/home-page-lines/Vector (6).png",
    right: "right-[4.6rem]",
    bottom: "-bottom-[10rem]",
  },
  {
    id: 8,
    img: "/assets/home-page-lines/Vector (7).png",
    right: "right-5",
    bottom: "-bottom-[9.5rem]",
  },
  {
    id: 9,
    img: "/assets/home-page-lines/Vector (8).png",
    right: "right-0",
    bottom: "-bottom-[6.5rem]",
  },
  {
    id: 10,
    img: "/assets/home-page-lines/Vector (9).png",
    right: "right-0",
    bottom: "-bottom-[4.2rem]",
  },
  {
    id: 11,
    img: "/assets/home-page-lines/Vector (10).png",
    right: "right-0",
    bottom: "-bottom-[2.3rem]",
  },
  {
    id: 12,
    img: "/assets/home-page-lines/Vector (11).png",
    right: "right-0",
    bottom: "-bottom-2",
  },
  {
    id: 13,
    img: "/assets/home-page-lines/Vector (12).png",
    right: "right-0",
    bottom: "bottom-0",
  },
  {
    id: 14,
    img: "/assets/home-page-lines/Vector (13).png",
    right: "right-0",
    bottom: "bottom-0",
  },
  {
    id: 15,
    img: "/assets/home-page-lines/Vector (14).png",
    right: "right-0",
    bottom: "bottom-0",
  },
];
