export const Lines = [
  { id: 1, img: "/assets/green-lines/l-1.png", offset: "right-20" },
  { id: 2, img: "/assets/green-lines/l-2.png", offset: "right-16" },
  { id: 3, img: "/assets/green-lines/l-3.png", offset: "right-20" },
  { id: 4, img: "/assets/green-lines/l-4.png", offset: "right-7" },
  { id: 5, img: "/assets/green-lines/l-5.png" },
  { id: 6, img: "/assets/green-lines/l-6.png" },
  { id: 7, img: "/assets/green-lines/l-7.png" },
  { id: 8, img: "/assets/green-lines/l-8.png" },
  { id: 9, img: "/assets/green-lines/l-9.png" },
  { id: 10, img: "/assets/green-lines/l-10.png" },
  { id: 11, img: "/assets/green-lines/l-11.png" },
  { id: 12, img: "/assets/green-lines/l-12.png" },
  { id: 13, img: "/assets/green-lines/l-13.png" },
  { id: 14, img: "/assets/green-lines/l-14.png" },
  { id: 15, img: "/assets/green-lines/l-15.png" },
  { id: 16, img: "/assets/green-lines/l-16.png" },
];

export const WhiteLines = [
  { id: 1, img: "/assets/white-lines/l-1.png", offset: "right-20" },
  { id: 2, img: "/assets/white-lines/l-2.png", offset: "right-16" },
  { id: 3, img: "/assets/white-lines/l-3.png", offset: "right-20" },
  { id: 4, img: "/assets/white-lines/l-4.png", offset: "right-7" },
  { id: 5, img: "/assets/white-lines/l-5.png" },
  { id: 6, img: "/assets/white-lines/l-6.png" },
  { id: 7, img: "/assets/white-lines/l-7.png" },
  { id: 8, img: "/assets/white-lines/l-8.png" },
  { id: 9, img: "/assets/white-lines/l-9.png" },
  { id: 10, img: "/assets/white-lines/l-10.png" },
  { id: 11, img: "/assets/white-lines/l-11.png" },
  { id: 12, img: "/assets/white-lines/l-12.png" },
  { id: 13, img: "/assets/white-lines/l-13.png" },
  { id: 14, img: "/assets/white-lines/l-14.png" },
  { id: 15, img: "/assets/white-lines/l-15.png" },
  { id: 16, img: "/assets/white-lines/l-16.png" },
];
